<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1dde8702-d233-402d-b93f-40a743706d59</elementGuidId>
    <imagePath></imagePath>
    <name>form_login_info</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/form[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'login_info')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>login_info</value>
        <webElementGuid>4fc66d49-42b8-451c-83bb-1665a3d737d5</webElementGuid>
    </webElementProperties>
</WebElementEntity>