<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0d34f9cb-06f7-4341-9d8d-9e093d7542b7</elementGuidId>
    <imagePath></imagePath>
    <name>input_continue</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#continue</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'continue') and equals(@name,'continue') and equals(@class,'submit-button btn btn_primary cart_button btn_action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>submit-button btn btn_primary cart_button btn_action</value>
        <webElementGuid>850992c2-db5c-4bed-9a9c-366b30ae9bc2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>5ea9ce96-b1ad-448d-969f-edbf443996d6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>606c652d-6f25-4fcf-a195-c99434600583</webElementGuid>
    </webElementProperties>
</WebElementEntity>