<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ee7543a9-a02f-480a-9783-3d0a0194c021</elementGuidId>
    <imagePath></imagePath>
    <name>input_first_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#first-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'first-name') and equals(@name,'firstName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>9a8e2b06-718e-40ce-8a90-84f571b13e4f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>first-name</value>
        <webElementGuid>9a88deff-c6bf-4cc4-9bef-87a570d04c2a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>firstName</value>
        <webElementGuid>14d9ba08-1b68-4109-b341-c126ba71cbd9</webElementGuid>
    </webElementProperties>
</WebElementEntity>