<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b92436e9-d4ad-4d27-add5-fc7d30c7b0e1</elementGuidId>
    <imagePath></imagePath>
    <name>img_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[alt='Herringbone\ Pine\ Tree']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'product-card-img is-img-loaded')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>product-card-img is-img-loaded</value>
        <webElementGuid>b80f732f-4b6c-4314-8fc7-a5edcfa3d86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>